name: Inward Safari
favicon: null
layout_spectrum: 0.36944
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78b2f2'
    - '#b77c63'
    - '#6b6942'
    - '#151515'
    - '#cbae8d'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
