name: The Inward Safari
favicon: null
layout_spectrum: 0.42474
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#404549'
    - '#7c605c'
    - '#7a8ca0'
    - '#ddd3c9'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
