name: The Inward Safari
favicon: null
layout_spectrum: 0.42474
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1f1f'
    - '#ac8f78'
    - '#f9f9f9'
    - '#605a4d'
    - '#afcd58'
  brandStrength: 0
  lightness: 0.4051466416567564
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
