name: The Inward Safari
favicon: null
layout_spectrum: 0.1227
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefa50'
    - '#ffffff'
    - '#7f7e9e'
    - '#000000'
    - '#b4450f'
  brandStrength: 0.1875
  lightness: 0.4051466416567564
  saturation: 0.31488781538791955
  rhythmicContrast: 0.9219883449841291
purpose: []
