name: The Inward Safari
favicon: null
layout_spectrum: 0.50156
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061117'
    - '#ffffff'
    - '#10437a'
    - '#9381b3'
    - '#e1c0ae'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
