name: Inward Safari
favicon: null
layout_spectrum: 0.36944
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bf36f5'
    - '#fec52e'
    - '#efcafb'
    - '#e8aa98'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
