name: The Inward Safari
favicon: null
layout_spectrum: 0.42474
typography_spectrum: 0.46165523095987737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00243e'
    - '#686e88'
    - '#f7fefe'
    - '#97abb6'
    - '#bfd2d6'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
